substitutions:
  name: esphome-web-0d4548
  friendly_name: rf-switch

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_encryption_key

# Allow Over-The-Air updates
ota:

# Allow provisioning Wi-Fi via serial
#improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

external_components:
  - source:
      type: local
      path: components
    
switch:
  - platform: rf_switch
    name: 'Leuchter'
    channel: 0
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Fenster'
    channel: 1
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Home'
    channel: 2
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Funk 03'
    icon: "mdi:power-socket-de"
    channel: 3
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Zaun'
    channel: 4
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Notlicht'
    channel: 5
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Deko'
    channel: 6
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Option'
    channel: 7
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Extras'
    channel: 8
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Outdoor'
    channel: 9
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Funk 11'
    icon: "mdi:power-socket-de"
    channel: 11
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Funk 12'
    icon: "mdi:power-socket-de"
    channel: 12
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Funk 13'
    icon: "mdi:power-socket-de"
    channel: 13
    output: rf_transmitter 
  - platform: rf_switch
    icon: "mdi:power-socket-de"
    name: 'Funk 14'
    channel: 14
    output: rf_transmitter 
  - platform: rf_switch
    icon: "mdi:power-socket-de"
    name: 'Funk 15'
    channel: 15
    output: rf_transmitter 
  - platform: rf_switch
    name: 'Master'
    channel: 10
    output: rf_transmitter 

  - platform: gpio
    name: 'Pumpe'
    icon: "mdi:water-pump"
    pin:
      number: GPIO16  #D0
      inverted: true
  - platform: gpio
    name: 'Brunnen'
    icon: "mdi:fountain"
    pin:
      number: GPIO5 #D1
      inverted: true
  - platform: gpio
    name: 'Gewächshaus-Boden'
    icon: 'mdi:water'
    pin: GPIO4  #D2
  - platform: gpio
    name: 'Gewächshaus-Sprinkler'
    icon: 'mdi:water'
    pin: GPIO14 #D5
  - platform: gpio
    name: 'Südwand-Terasse'
    icon: 'mdi:water'
    pin: GPIO13 #D7
  - platform: gpio
    name: 'Hochbeete-Rasen'
    icon: 'mdi:water'
    pin: GPIO15 #D8

output:
  - platform: rf_outlet
    id: rf_transmitter
    pin: GPIO12 #D6
    repeat: 6
